[package]
name = "bevy_voxel_render"
version = "0.0.1"
edition = "2021"
description = "Provides rendering functionality for Bevy Engine"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "voxel"]

[dependencies]
bevy_render = { version = "0.14.2" }
