[package]
name = "soulflame"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.2", default-features = false, features = ['bevy_scene', 'bevy_winit', "bevy_audio", 'bevy_asset'] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3